version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_app
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  db_data:
